[package]
name = "bake_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
syntect = { workspace = true }
two-face = "0.4.3"
