[package]
name = "music-export"
version = "0.1.0"
edition = "2024"

[dependencies]
paxsite-music = { path = "../paxsite-music" }
blackbird-shared = { workspace = true }
blackbird-state = { workspace = true }

anyhow = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
